name: Run GO Build & Test

on:
  pull_request:
    types: [ opened, reopened, edited, synchronize ]
    paths: [ "internal/*", "cmd/*" ]
    
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up GO
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Display Go version
      run: |
        echo "::notice:: Go version is $(go version)"
    
    - name: build
      run: go build -o bin/vpc-cidr-manager