name: Run GO Lint and Staticcheck

on:
  push:
    branches: '*'

jobs:
  lint:
    name: Run go vet and staticcheck
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up GO Environment
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Display Go version
      run: |
        echo "::notice:: Go version is $(go version)"

    - name: Install dependencies
      run: go mod download

    - name: Run go vet
      run: go vet .

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck .

